#!/bin/tcsh
# submit with qsub < [job.lsf]
# walltime = 5hrs for 1 var

#PBS -N biweekly_avg
#PBS -A P48500028
#PBS -q regular
#PBS -l select=1:ncpus=12:mpiprocs=12
#PBS -l walltime=02:00:00
#PBS -m abe
#PBS -M sarah.a.baker@colorado.edu

mkdir -p /glade/scratch/sabaker/temp
setenv TMPDIR /glade/scratch/sabaker/temp
setenv MPI_SHEPHERD true

### Run the executable
mpiexec_mpt launch_cf.sh /glade/u/home/sabaker/cfsv2/scripts/avg_biweekly.jobs.txt
