#!/bin/tcsh
# submit with qsub < [job.lsf]
# walltime is >0.5hr per var

#PBS -N ens.biwk.avg
#PBS -A P48500028
#PBS -q regular
#PBS -l select=2:ncpus=6:mpiprocs=6:mem=109GB
#PBS -l walltime=0:30:00
#PBS -m abe
#PBS -M sarah.a.baker@colorado.edu


mkdir -p /glade/scratch/sabaker/temp
setenv TMPDIR /glade/scratch/sabaker/temp
setenv MPI_SHEPHERD true

### Run the executable
mpiexec_mpt launch_cf.sh /glade/u/home/sabaker/cfsv2/scripts/ensAverage.jobs.txt

